-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 03:14:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voters` DEFAULT CHARACTER SET utf8 ;
USE `voters` ;

-- -----------------------------------------------------
-- Table `voters`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voters`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(85) NOT NULL,
  `vote_num` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voters`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voters`.`vote` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_belong` INT UNSIGNED NOT NULL,
  `topic` VARCHAR(100) NOT NULL,
  `desc` TEXT NOT NULL,
  `vote_able` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `create_time` INT UNSIGNED NOT NULL,
  `overdue_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `multi_num` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `user_belong_idx` (`user_belong` ASC),
  CONSTRAINT `user_belong`
    FOREIGN KEY (`user_belong`)
    REFERENCES `voters`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voters`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voters`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vote_id` INT UNSIGNED NOT NULL,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `desc` TEXT NOT NULL,
  `desc_pic_url` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `vote_id_idx` (`vote_id` ASC),
  CONSTRAINT `vote_id`
    FOREIGN KEY (`vote_id`)
    REFERENCES `voters`.`vote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
